project:
  type: website


format:
  html:
    page-layout: article
    toc: true
    code-fold: true
    theme: 
      light: flatly
      dark: darkly
    code-tools: true
      

website:
  title: "AE2010/AE2011"
  page-navigation: true
  navbar:
    left:
      - text: "Home"
        file: index.ipynb
      - text: "Notebooks"
        file: index.ipynb
    right:
      - icon: github
        href: https://github.com/psesh/ae2010-11
        aria-label: GitHub
  sidebar:
    title: "AE2010/11"
    search: true
    style: "docked"
    contents:
      - index.ipynb
      - section: "Practice Problems"
        contents: 
          - practice_problems/incompressible_fluid_mechanics.ipynb
          - practice_problems/thermodynamics.ipynb
      - section: "Notebooks"
        contents:
          - demo.ipynb
          - for_loops.ipynb
          - vector_fields.ipynb
          - couette_flow.ipynb
          - poiseuille_flow.ipynb
          - flow_around_bend.ipynb
          - normal_shocks.ipynb
          - supersonic_flow_friction.ipynb
          - dataframes.ipynb
      - section: "Examples"
        contents:
          - sample_problems/lecture_2.ipynb
          - sample_problems/lecture_3.ipynb
          - sample_problems/lecture_4.ipynb
          - sample_problems/lecture_5.ipynb
          - sample_problems/lecture_6.ipynb
          - sample_problems/lecture_9.ipynb
          - sample_problems/lecture_10.ipynb
          - sample_problems/lecture_12.ipynb
          - sample_problems/lecture_13.ipynb
          - sample_problems/lecture_14.ipynb
          - sample_problems/lecture_15.ipynb
          - sample_problems/lecture_16.ipynb
          - sample_problems/lecture_17.ipynb
          - sample_problems/lecture_18.ipynb
          - sample_problems/lecture_19.ipynb
          - sample_problems/lecture_21.ipynb