project:
  type: website


format:
  html:
    page-layout: article
    toc: true
    code-fold: true
    theme: 
      light: flatly
      dark: darkly
    code-tools: true
      

website:
  title: "AE2010/AE2011"
  page-navigation: true
  navbar:
    left:
      - text: "Home"
        file: index.ipynb
      - text: "Notebooks"
        file: index.ipynb
    right:
      - icon: github
        href: https://github.com/psesh/ae2010-11
        aria-label: GitHub
  sidebar:
    title: "AE2010/11"
    search: true
    style: "docked"
    contents:
      - index.ipynb
      - section: "Notebooks"
        contents:
          - demo.ipynb
          - flow_around_bend.ipynb
          - couette_flow.ipynb
          - poiseuille_flow.ipynb
          - normal_shocks.ipynb
          - supersonic_flow_friction.ipynb
      - section: "Examples"
        contents:
          text: "L2"
          file: sample_problems/lecture_2.ipynb